In [ ]:
# import libraries
import numpy as np  # type: ignore

In [ ]:
# แสดงเลขสุ่ม 1 ตัว ระหว่าง 1-100
num = np.random.randint(1, 100)

(num)

86

In [ ]:
# ตรวจสอบว่าเลขคู่หรือเลขคี่
(num % 2 == 0)

True

In [ ]:
# ตรวจสอบว่าเลขคู่หรือเลขคี่
(num % 2 == 1)  

False

In [ ]:
# แสดงเลข 1-10
num = np.array([1,2,3,4,5,6,7,8,9,10])

(num)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# แสดงเลข index ที่ 0
(num[0])

np.int64(1)

In [ ]:
# แสดงค่าที่เป็นเลขคู่
(num[1::2])

array([ 2,  4,  6,  8, 10])

In [ ]:
# แสดงค่าที่เป็นเลขคี่
(num[0::2])

array([1, 3, 5, 7, 9])